GET http://localhost:3000

###send error http
GET http://localhost:3000/abc_xyz

###login route
POST http://localhost:3000/auth/login

###register route
POST http://localhost:3000/auth/register
Content-Type:application/json

{
 "email": "janedoe@yahoo.com",
 "password": "123456"
}

###refresh-token route
POST http://localhost:3000/auth/refresh-token

###logout route
DELETE http://localhost:3000/auth/logout

