GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTE4MTQzOTMsImV4cCI6MTYxMTgzMjM5MywiYXVkIjoiNjAxMjJhOGRmNjcyZDAyZWM0Y2Q1YWEzIiwiaXNzIjoibXl3ZWJzaXRlLmNvbSJ9.tWktoJtKoPytebHHYW6U4h-yeGDxaeBkh6E2RqfWs58

###send error http
GET http://localhost:3000/abc_xyz

###login route
POST http://localhost:3000/auth/login
Content-Type:application/json

{
 "email": "johndoe@yahoo.com",
 "password": "123456"
}

###register route
POST http://localhost:3000/auth/register
Content-Type:application/json

{
 "email": "janedoe@yahoo.com",
 "password": "123456"
}

###refresh-token route
POST http://localhost:3000/auth/refresh-token

###logout route
DELETE http://localhost:3000/auth/logout

